import Vue from "vue";
declare const _default: import("vue/types/vue").ExtendedVue<Vue, {
    element: HTMLDivElement;
    resizeObserver: ResizeObserver | null;
    calculatedHeight: string;
    calculatedWidth: string;
    calculateTop: string;
    calculateLeft: string;
    limitedTop: string | null;
    limitedLeft: string | null;
    preFullScreenStyle: any;
    reachedMinSize: boolean;
    reachedMaxSize: boolean;
    minWidth: number;
    maxWidth: number | undefined;
    minHeight: number;
    maxHeight: number | undefined;
    internalPinned: boolean;
    internalResizable: boolean;
    pos1: number;
    pos2: number;
    pos3: number;
    pos4: number;
    _bottom: number;
    _left: number;
    _right: number;
    _top: number;
    rect: DOMRect;
    resizing: boolean;
    resizeHandle: string;
    initialRect: DOMRect | null;
    coords: string[];
    isFullScreen: Boolean;
    isMinimized: Boolean;
    savedPosition: null;
    currentWidth: string;
    currentHeight: string;
    insetRight: string;
}, {
    doInitialMeasurements(): void;
    dragMouseDownHandler(e: MouseEvent): void;
    setDraggableBodyHeight(): void;
    updateCalculatedSize(): void;
    observeExternalResize(): void;
    applyStyleWithImportant(height?: string | null | undefined, width?: string | null | undefined, position?: string | null | undefined, top?: string | null | undefined, left?: string | null | undefined, bottom?: string | null | undefined, right?: string | null | undefined): void;
    closeDragElement(): void;
    elementDrag(mouseEvent: MouseEvent): void;
    elementMobileDrag(mouseEvent: TouchEvent): void;
    dragMouseDown(mouseEvent: MouseEvent): void;
    dragElement(elmnt: HTMLDivElement): void;
    closePopup(): void;
    toggleFullscreen(): void;
    minimizeWindow(): void;
    resizeMouseDown(event: MouseEvent, handle: "top-left" | "top-right" | "bottom-left" | "bottom-right"): void;
    resizeMouseMove(event: any): void;
    resizeMouseUp(): void;
    clickEvent(e: Event): void;
    fixZIndex(): void;
    configureForEditor(): void;
}, {
    classObject: {
        [x: string]: any;
        minimized: any;
    };
}, {
    width: string;
    height: string;
    headerPadding: string;
    right: string;
    left: string;
    top: string;
    bottom: string;
    zIndex: string;
    pinned: boolean;
    backgroundColor: string;
    _renderingProps: any;
    class: string;
    border: boolean;
    closeBtn: boolean;
    fullScreen: boolean;
    resizable: boolean;
    minimizable: boolean;
}>;
export default _default;
//# sourceMappingURL=QLightBox.vue.d.ts.map