import Vue from "vue";
declare const _default: import("vue/types/vue").ExtendedVue<Vue, {
    displayDateFormat: string | undefined;
    serviceDateFormat: string | undefined;
    vuetifyDateFormat: string;
    valueInternal: string | string[] | null;
    internalValue: any;
    dateFormatted: string;
    menu1: boolean;
    idTest: string | null;
    isDateChangedBefore: boolean;
    monthFormat: string;
    isClickClear: boolean;
    uniqueID: string;
}, {
    resurrect(): void;
    changeMenuValue(): void;
    onKeyUp(event: any): void;
    onBlur(event: any): void;
    onFocus(event: any): void;
    onKeyDown(event: any): void;
    initialize(): void;
    changeValueInternal(newValue: any, oldValue: any): void;
    getDisplayFormat(): any;
    getServiceFormat(): any;
    CreateGuid(): string;
    textinput(): void;
    resetValue(): void;
    reset(): void;
    resetValidation(): void;
    validationRefs(): (Element | Vue | Vue[] | Element[])[];
    arraysEqual(a: any, b: any): boolean;
    DateChange(): void;
}, {
    parsedDate: {
        seperateChar: string;
        splittedFormat: string[] | undefined;
        year: number;
        month: number;
        date: number;
    };
}, {
    openOnlyIconClick: boolean;
    allowedDates: Function;
    clearable: boolean;
    weekdayFormat: Function;
    placeHolder: string;
    firstDayOfWeek: string | number;
    value: string;
    hideDetails: string | boolean;
    hideMenu: boolean;
    hint: string;
    outlined: boolean;
    type: string;
    willAttach: boolean;
    persistentHint: boolean;
    persistentPlaceholder: boolean;
    readonlyDatepicker: boolean;
    readonlyTextField: boolean;
    rounded: boolean;
    multiple: boolean;
    range: boolean;
    disabled: boolean;
    min: string;
    max: string;
    label: string;
    _renderingProps: any;
    rules: unknown[];
    dateNow: boolean;
    locale: string;
    dense: boolean;
    filled: boolean;
    textFieldClass: string;
    separateChar: string;
    height: string | number;
    tabindex: string | number;
    solo: boolean;
    soloInverted: boolean;
    prependInnerIcon: string;
    displayFormat: string;
    DiscardSettings: boolean;
    noTitle: boolean;
    headerColor: string;
    titleDateFormat: Function;
}>;
export default _default;
//# sourceMappingURL=VInlineDatepicker.vue.d.ts.map